### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by phbaars** [reinzor/gst-mmal#1]
While trying to build the software for the video wall I encountered issues. Gst-mmal turns out to be the cause. git clone works fine. autogen.sh too. When I type "make" there are a load of warnings "redundand declaration of vcos_blockpool_extend" but building continues.
It ends with: gstmmalglupload.c:726:20: error: GL_TEXTURE_EXTERNAL_OES undeclared.
Make[2] ***[makefile:722: libgstmmal_la-gstmmalglupload.lo] Error 1.
make: ***[Makefile:444 all] Error 2.

I started with a clean Stretch op Raspberry Pi 2b and followed the description exactly.
What can be wrong?

**Comment by reinzor** [comment]
Did you try my installation script in the videowall repo https://github.com/reinzor/videowall/blob/master/install_raspberry_pi_stretch_lite_autostart.bash ?

**Comment by phbaars** [comment]
I thought I downloaded Stretch Lite. However, it turned out to be Buster Lite. This works much better :)
